version: "3"

services:
    tensorflow:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: tensorflow-service
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]
        command: bash -c "while sleep 1000; do :; done"
        volumes:
            - ..:/app
